### ISSUE TITLE
Add link to quoted message

### ISSUE THREAD

**Issue by pole95** [HansTrashy/trashy_bot#15]
**Is your feature request related to a problem? Please describe.**
When posting a quote, provide a way to access the context of the quoted message.

**Describe the solution you'd like**
Provide a link to the message, either via a reaction or in the embedded quote itself.

**Describe alternatives you've considered**
Nein

**Additional context**
Hans hat gesagt ich soll issue aufmachen

**Comment by HansTrashy** [comment]
You can now receive the message with the ℹ️ reaction on it
