### ISSUE TITLE
Shiny charity tracker for #pokemongo

### ISSUE THREAD

**Issue by maxjarma** [HansTrashy/trashy_bot#16]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A command that lets us (the users of #pokemongo) track donation amounts each user has to do.
Maybe like this: $shiny @username moneyamount(as a number). Bot adds said number to the existing account of the pinged user and returns a message with the new account value. 
A nice to have would be not allowing users to execute the command for others to not falsify the number. Mods should be excluded from this and should always be able to execute the command for others.

**Describe alternatives you've considered**
Tracking in an Excel sheet but that's too much effort

**Additional context**
https://canary.discordapp.com/channels/217015995385118721/469104845702430722/612776657140318228
p :raised_hands:

**Comment by IfaqYurmama** [comment]
Es ist Deutschland hier!
