### ISSUE TITLE
$katzer damit der Müllbot die lustige Katze postet Ekki findet das witzig und ich finde das auch witzig

### ISSUE THREAD

**Issue by maxjarma** [HansTrashy/trashy_bot#17]
**Is your feature request related to a problem? Please describe.**
Nö

**Describe the solution you'd like**
Der Bot soll die lustige Katze posten wenn ich $katzer mache :katzer: Ekki

**Describe alternatives you've considered**
Nö

**Additional context**
:pepega: :mega: HAAAAAAAAAAAANS mach bitte

**Comment by pole95** [comment]
Hallo hans, $misc emoji katzer ist nicht $katzer, fix pls
