### ISSUE TITLE
$katzer funktioniert nicht muss ein Bug oder so sein

### ISSUE THREAD

**Issue by maxjarma** [HansTrashy/trashy_bot#18]
**Describe the bug**
Wenn ich $katzer mache kommt kein Katzer

**To Reproduce**
1. Go to 'Chat'
2. Click on 'Textbox'
3. Scroll down to '$katzer'

**Expected behavior**
Er postet den Katzer

**Screenshots**
Nö

**Additional context**
HAAAAAAAAAAAANS

**Comment by HansTrashy** [comment]
Duplicate issue of #17
