### ISSUE TITLE
Bot gönnt nie

### ISSUE THREAD

**Issue by maxjarma** [HansTrashy/trashy_bot#23]
**Describe the bug**
Jedes mal wenn ich $choose benutze nimmt der Bot die einzige Option, die keine Freude stiftet

**To Reproduce**
1. Gib ein $choose Command ein
2. Klicke Nachricht senden
3. Der Bot pickt die Option, die nicht am gönnen ist
4. Grrrrr

**Expected behavior**
Bot gönnt und pickt was nettes

**Screenshots**
https://imgur.com/vRmSGMC

**Additional context**
HAAAAAAAAANS geh gönnen Dinge

**Comment by HansTrashy** [comment]
Working as intended
