### ISSUE TITLE
Server-wide favs

### ISSUE THREAD

**Issue by JonSnowWhite** [HansTrashy/trashy_bot#26]
**Describe the bug**
Bot only posts favs from different servers than the server the command was issued on

**To Reproduce**
1. Go to \<server\>
2. Click on $fav irgendwas
3. Scroll down to bot message
4. See that bot only uses favs done on different server

**Expected behavior**
Bot should not only answer with favs from other servers but with favs from the current one as well

**Comment by HansTrashy** [comment]
Fixed by https://github.com/HansTrashy/trashy_bot/commit/2ece1c0c5a7cf31c86b98945e101b5b7c6021545
