### ISSUE TITLE
Cannot fav or quote Käsespätzle with Ketchup

### ISSUE THREAD

**Issue by NilsDeckert** [HansTrashy/trashy_bot#33]
**Describe the bug**
Neither '$fav Spätzle', nor '$quote https://discord.com/channels/217015995385118721/256362274044903424/643174123056660510' return the expected result. Using the '$fav' feature does not result in any answer, while the '$quote' command states, that the message could not be found. Clearly, this must be a mistake

**To Reproduce**
1. Type '$fav Spätzle' (Alter this step to fit your tag name)
2. Hit Enter
3. TrashyBot does not respond in any way

**Expected behavior**
![Spätzle](https://media.discordapp.net/attachments/256362274044903424/643174122511138846/IMG_20191110_204150.jpg?width=1248&height=702)

**Screenshots**
![image](https://user-images.githubusercontent.com/42399937/133944263-1b4d4153-411e-4eb2-916b-7485537a4c86.png)
![image](https://user-images.githubusercontent.com/42399937/133944271-69ea5fd3-a515-473e-b61d-c5def9cbd96c.png)

**Comment by HansTrashy** [comment]
This results through mods removing access for the trashy bot to #essen-trinken cant fix
